### ISSUE TITLE
"configure" fails if user fails to read manual and uses "autoconf" instead of "autoreconf"

### ISSUE THREAD

**Issue by nkurz** [novaprova/novaprova#13]
It's been a while since I've used autoconf, and since I couldn't find an INSTALL file, I took a stab and tried "autoconf" followed by "configure".    "autoconf" ran without error, but "configure" died with an unhelpful syntax error: 

./configure: line 2142: syntax error near unexpected token `libxml,'
./configure: line 2142:`    PKG_CHECK_MODULES(libxml, $p, libxml=$p;break)'

This confused me because I have both libxml and pkg-config installed.  Eventually I figured out that this meant that the PKG_CHECK_MODULES macro was not being found.   One theory is that it's safer to skip the macros (http://tirania.org/blog/archive/2012/Oct-20.html), but I have no opinion.  

I tried looking again for installation instructions, and eventually found the excellent ones in "doc/manual/getting-started.rst".   Once I followed those (switching from "autoconf" to "autoreconf -iv") everything worked as designed.   

Could I suggest that you do something like "ln -s doc/manual/getting-started.rst INSTALL" so that the instructions are found in a more standard location? 

Thanks for writing excellent software.

**Comment by gnb** [comment]
G'day nkurz,

Thanks for trying NovaProva.

Sorry about your awkward and confusing experience with autotools. I also
realize that most experiences with autotools are awkward and confusing, as
it's an unnecessarily complex and brittle constellation of tiny
semi-independent things each designed to do a simple job badly. But it's
the standard so yay.

That blog post is quite amusing, although to me it's like comparing the
relative merits of food poisoning or pneumonia.

I will definitely follow your suggestion and make the instructions more
discoverable.


On Tuesday, March 22, 2016, nkurz <notifications@github.com> wrote:

> It's been a while since I've used autoconf, and since I couldn't find an
> INSTALL file, I took a stab and tried "autoconf" followed by "configure".
> "autoconf" ran without error, but "configure" died with an unhelpful syntax
> error:
>
> ./configure: line 2142: syntax error near unexpected token libxml,'
> ./configure: line 2142: PKG_CHECK_MODULES(libxml, $p, libxml=$p;break)'
>
> This confused me because I have both libxml and pkg-config installed.
> Eventually I figured out that this meant that the PKG_CHECK_MODULES macro
> was not being found. One theory is that it's safer to skip the macros (
> http://tirania.org/blog/archive/2012/Oct-20.html), but I have no opinion.
>
> I tried looking again for installation instructions, and eventually found
> the excellent ones in "doc/manual/getting-started.rst". Once I followed
> those (switching from "autoconf" to "autoreconf -iv") everything worked as
> designed.
>
> Could I suggest that you do something like "ln -s
> doc/manual/getting-started.rst INSTALL" so that the instructions are found
> in a more standard location?
>
> Thanks for writing excellent software.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/novaprova/novaprova/issues/13>
>


-- 
Greg.

**Comment by gnb** [comment]
This was fixed in commit eeb991f back on 2016-03-23.
