### ISSUE TITLE
doxygen warnings for current master

### ISSUE THREAD

**Issue by nkurz** [novaprova/novaprova#14]
Build of current master on Ubuntu 14.04 / Linux 4.4.4 / g++ 5.3.0 is wonderfully clean except for a few warnings from doxygen.  They probably aren't an issue, but thought it's worth mentioning in case you weren't aware of them. 

nate@skylake:~/git/novaprova$ doxygen --version
1.8.6

nate@skylake:~/git/novaprova$ make
...
doxygen
Warning: Tag `SYMBOL_CACHE_SIZE' at line 304 of file Doxyfile has become obsolete.
To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
Warning: Tag`SHOW_DIRECTORIES' at line 488 of file Doxyfile has become obsolete.
To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
Warning: Tag `HTML_ALIGN_MEMBERS' at line 814 of file Doxyfile has become obsolete.
To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
Warning: argument`HIERARCHIES' for option GENERATE_TREEVIEW is not a valid boolean value
Using the default: NO!
Warning: doxygen no longer ships with the FreeSans font.
You may want to clear or change DOT_FONTNAME.
Otherwise you run the risk that the wrong font is being used for dot generated graphs.
...

Running doxygen -u as suggested removes the first 3 warnings but leaves the last two.

**Comment by gnb** [comment]
G'day,

Ah doxygen how I do love thee.

These warnings still exist because I found it impossible to construct a
Doxyfile which works cleanly on any three Linux distros.
Doxygen's configuration is just too volatile. At least they're just
warnings.

I'd accept patches to remove warnings as long as they don't affect the xml
or man outputs, which are the ones still used. Generating HTML happens via
Sphinx now.

Greg.

On Tuesday, March 22, 2016, nkurz <notifications@github.com> wrote:

> Build of current master on Ubuntu 14.04 / Linux 4.4.4 / g++ 5.3.0 is
> wonderfully clean except for a few warnings from doxygen. They probably
> aren't an issue, but thought it's worth mentioning in case you weren't
> aware of them.
>
> nate@skylake:~/git/novaprova$ doxygen --version
> 1.8.6
>
> nate@skylake:~/git/novaprova$ make
> ...
> doxygen
> Warning: Tag SYMBOL_CACHE_SIZE' at line 304 of file Doxyfile has become
> obsolete.
> To avoid this warning please remove this line from your configuration file
> or upgrade it using "doxygen -u"
> Warning: TagSHOW_DIRECTORIES' at line 488 of file Doxyfile has become
> obsolete.
> To avoid this warning please remove this line from your configuration file
> or upgrade it using "doxygen -u"
> Warning: Tag HTML_ALIGN_MEMBERS' at line 814 of file Doxyfile has become
> obsolete.
> To avoid this warning please remove this line from your configuration file
> or upgrade it using "doxygen -u"
> Warning: argumentHIERARCHIES' for option GENERATE_TREEVIEW is not a valid
> boolean value
> Using the default: NO!
> Warning: doxygen no longer ships with the FreeSans font.
> You may want to clear or change DOT_FONTNAME.
> Otherwise you run the risk that the wrong font is being used for dot
> generated graphs.
> ...
>
> Running doxygen -u as suggested removes the first 3 warnings but leaves
> the last two.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/novaprova/novaprova/issues/14>
>


-- 
Greg.

**Comment by gnb** [comment]
Reading back it seems I decided not to fix this.
