### ISSUE TITLE
clearing an object of non-trivial type 'class np::event_t

### ISSUE THREAD

**Issue by cpackham** [novaprova/novaprova#27]
GCC 8.3 complains about the following line of code

https://github.com/novaprova/novaprova/blob/770781f2b27f461c99342ed39547f69582f6a7ca/np/event.cxx#L92

Doing some googling I think this is saying that norm should be declared using an initializer instead `static event_t norm(which=this.which);` but I don't know enough modern C++ to be sure. Plenty of other suggestions just cast to `void *` to avoid the error. Hence I'm just raising this as an issue instead of attempting to fix it myself.

**Comment by gnb** [comment]
Closing this report.  Thanks again for your fix @cpackham
