### ISSUE TITLE
Build error on 1.5rc1 branch

### ISSUE THREAD

**Issue by cpackham** [novaprova/novaprova#35]
I've been working around this but I figured I may as well create an issue for it. It is even something I might be able to fix myself.

Following the docs to build from git https://novaprova.readthedocs.io/en/latest/getting-started.html#from-read-only-git I get the following complaint from autoreconf
```
Step 9/12 : RUN autoreconf -vi &&     ./configure &&     make &&     make install
 ---> Running in 23ea24dff567
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf
autoreconf: running: /usr/bin/autoheader
autoreconf: configure.ac: not using Automake
autoreconf: Leaving directory `.'
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
The command '/bin/sh -c autoreconf -vi &&     ./configure &&     make &&     make install' returned a non-zero code: 1
```

The same build recipe works fine on master.

[Dockerfile.txt](https://github.com/novaprova/novaprova/files/4596558/Dockerfile.txt)

attached is a Dockerfile that illustrates the issue.

**Comment by gnb** [comment]
Yes, the build instructions grew a new step in 1.5

```
automake -ac   # ignore errors
autoreconf -iv
./configure
make
make install
```

Some of the documentation has been updated, but hasn't been published yet.

**Comment by cpackham** [comment]
OK cool.
